### ISSUE TITLE
Null pointer exception on opening SDK

### ISSUE THREAD

**Issue by qbobaid** [zoho/salesiq-sdk-android-sample#2]
I migrated my android application to androidX and after that I am experiencing the following error..

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.app/com.zoho.livechat.android.ui.activities.SalesIQActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.graphics.drawable.Drawable.setColorFilter(int, android.graphics.PorterDuff$Mode)' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2572)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2654)
        at android.app.ActivityThread.-wrap11(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1488)
        at android.os.Handler.dispatchMessage(Handler.java:111)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:5728)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.graphics.drawable.Drawable.setColorFilter(int, android.graphics.PorterDuff$Mode)' on a null object reference
        at com.zoho.livechat.android.ui.activities.SalesIQActivity.onCreate(SalesIQActivity.java:131)
        at android.app.Activity.performCreate(Activity.java:6368)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1113)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2519)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2654) 
        at android.app.ActivityThread.-wrap11(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1488) 
        at android.os.Handler.dispatchMessage(Handler.java:111) 
        at android.os.Looper.loop(Looper.java:207) 
        at android.app.ActivityThread.main(ActivityThread.java:5728) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)

it is working properly in support version

**Comment by Angu-G** [comment]
@qbobaid  Fix is in our following beta version. Please update kindly.

implementation 'com.zoho.salesiq:mobilisten:1.5-beta.4.1'

We will be rolling out this fix in our upcoming release.

**Comment by qbobaid** [comment]
Thanks. working now.
One question.. will the message from chat main screen "we at TechSoft Studio would be more than happy to help you...." be removed  in upcoming release?

**Comment by Angu-G** [comment]
Hello @qbobaid , can we get more detailed information from your side.

**Comment by Angu-G** [comment]
Issue is marked as open until we roll out this fix in major release.
